spring.datasource.url=jdbc:postgresql://localhost:5435/telegrambot
spring.datasource.username=tg_bot_user
spring.datasource.password=strong_password
telegram.bot.token=8067438271:AAGXXoUp8Um_GfasDHNegiZhZ5WY8ApgFWE

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=none

logging.level.liquibase=info
